In [1]:
import sys
sys.path.append('../upd')

import numpy as np

from Hamiltonian import HamiltonianAPI
from Huckel_Hamiltonian import *

[0, 1]


Initializing dense array

In [2]:
norb = 2
nelec = norb
hubbard = Hubbard([(f"C{i}",f"C{i+1}", 1) for i in range(1,norb)], alpha=0, beta=-1, 
                  u_onsite=np.array([1 for i in range(norb)]))
ecore, h, v = hubbard.get_hamilton()

In [3]:
print('printing one-electron integrals as a dense array:\n', h)
print('printing two-electron integrals as a dense array:\n', v)

printing one-electron integrals as a dense array:
 [[ 0. -1.]
 [-1.  0.]]
printing two-electron integrals as a dense array:
 [[[[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 0.  0.  1.  0.]
   [ 0.  0.  0. -0.]
   [-1.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]]


 [[[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 0.  0. -0.  0.]
   [ 0.  0.  0.  1.]
   [ 0.  0.  0.  0.]
   [ 0. -1.  0.  0.]]]


 [[[ 0.  0. -1.  0.]
   [ 0.  0.  0.  0.]
   [ 1.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]
   [ 0.  0.  0.  0.]]

  [[ 0.  0.

In [4]:
print('converting one-elctron integrals in dense array to sparse array format and printing:')
hs = hubbard.to_sparse(h); print(hs)
print('converting two-elctron integrals in dense array to sparse array format and printing:')
vs = hubbard.to_sparse(v); print(vs)

converting one-elctron integrals in dense array to sparse array format and printing:
  (0, 1)	-1.0
  (1, 0)	-1.0
converting two-elctron integrals in dense array to sparse array format and printing:
  (2, 2)	1.0
  (2, 8)	-1.0
  (7, 7)	1.0
  (7, 13)	-1.0
  (8, 2)	-1.0
  (8, 8)	1.0
  (13, 7)	-1.0
  (13, 13)	1.0


In [5]:
print('converting one-elctron integrals in sparse array to dense array format and printing:')
hd = hubbard.to_dense(hs); print(hd)
print('converting two-elctron integrals in sparse array to dense array format and printing:')
vd = hubbard.to_dense(vs); print(vd)
print('converting two-elctron integrals in sparse array to dense array format and printing:')
vd = hubbard.to_dense(vs,4); print(vd)

print(hd == h)
print(vd == v)

converting one-elctron integrals in sparse array to dense array format and printing:
[[ 0. -1.]
 [-1.  0.]]
converting two-elctron integrals in sparse array to dense array format and printing:
[[ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  1.  0.  0.  0.  0.  0. -1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0. -1.  0.  0.]
 [ 0.  0. -1.  0.  0.  0.  0.  0.  1.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.  0.]
 [ 