# Rauk's table and Wolfsberrg-Helmholz approximation

So far the Hamiltonians treated by the documentation have been focused in carbon chains. With this new update it is possible to work with different atoms, using the Rauk's table or the distance beetween the atoms with the Wolfsberrg-Helmholz aproximation.

To generate a Hamiltonian with atoms different from carbon, simply apply the same logic as before: Define a list of tuples with the atoms indexed by the position of their respective site in the compound. The new module of the library has two main purposes:

1) If you define the system using atoms different from carbons and the connectivity as ``integer`` numbers, the program will assign to the one body term the $\alpha$ and $\beta$ precomputed based on the Rauk's table.

2) If you define the system using atoms different from carbons and the connectivity as `float` numbers, the program will assign to the one body term the $\alpha$ and $\beta$ computed using the Wolfsberrg-Helmholz approximation, based on the provided distance.



## Example: Rauk's table

Suppose that you want to define a Hubbard model assigning the values based on the Rauk's table. You can do this based on the example below. 


In [1]:
import sys  
sys.path.insert(0, '../')
import numpy as np
from moha import HamHub


system = [('C1', 'Cl2', 1), ('Cl2', 'F3', 1),
                    ('F3', 'Si4', 1), ('Si4', 'C1', 1)]
hubbard = HamHub(system, u_onsite=np.array([1, 1]))

print(hubbard.generate_one_body_integral(dense=True, basis='spatial basis'))

[[-0.414    -0.033046  0.       -0.039975]
 [-0.033046 -0.492884 -0.027183  0.      ]
 [ 0.       -0.027183 -0.558443 -0.009061]
 [-0.039975  0.       -0.009061 -0.414   ]]


## Example:  Wolfsberrg-Helmholz approximation

Suppose now that you want to define the same system, but computing the parameters based on the overlap distance beetween the neighbors atoms. You can do that using the example below.

The values of $\alpha$ and $\beta$ are computed based on the following formulas:


$$
\alpha_X = -(\text{ionization potential of atom X})
$$

The $\beta$ value for the interaction between atom X and atom Y is defined as:

$$
\beta_{XY} = 1.75 S_{XY} \frac{\alpha_X + \alpha_Y}{2}
$$

In [2]:
import sys  
sys.path.insert(0, '../')
import numpy as np
from moha import HamHub


system = [('C1', 'Cl2', 1.5), ('Cl2', 'F3', 1.8),
                    ('F3', 'Si4', 1.8), ('Si4', 'C1', 1.7)]
hubbard = HamHub(system, u_onsite=np.array([1, 1]))

print(hubbard.generate_one_body_integral(dense=True, basis='spatial basis'))

[[-0.41380839 -0.73648465  0.         -0.56460276]
 [-0.73648465 -0.47655051 -0.84086439  0.        ]
 [ 0.         -0.84086439 -0.64027609 -0.54414171]
 [-0.56460276  0.         -0.54414171 -0.29956945]]


# Example: Usage with molecules 

If you want to make a chain using molecules you can use the following structure: pass the atom $X_n$ in the position m, the tuple would have the following form `Xm(n)`. Below it's possible to see a example of this. 

In [3]:
from moha import HamHuck


N2_O1_P2 = HamHuck([('N1(2)', 'O2(1)', 1), ('O2(1)', 'P3(2)', 1), ('P3(2)', 'N1(2)', 1)])
h1 = N2_O1_P2.generate_one_body_integral(dense=True, basis='spatial basis')
print(h1)

[[-0.441183 -0.060762 -0.041574]
 [-0.060762 -0.465701 -0.039975]
 [-0.041574 -0.039975 -0.424127]]


## Example: Defining the dictionaries 

It is also possible to define your own dictionary, basically pass the dictionaries following the structure:

1) `atom_dictionary = {'atom1': alpha1, 'atom2': alpha2}`
2) `bond_dictionary = {'atom1atom2': beta}`

In [4]:
import sys  
sys.path.insert(0, '../')
import numpy as np
from moha import HamHub

# First way to define the Hamiltonian
# two site Hubbard model

# system = [('C1', 'C2', 1)] is a list of tuples, where each tuple represents a bond
# between two atoms and the third element is the type of bond (singe or double).
# For now, we only support single bonds between carbon atoms. 
# For this type of bonds the default values of alpha and beta are -0.414 and -0.0533, respectively.
# In the future we are planning to support different types of bonds for different atoms.
system = [('C1', 'Cl2', 1), ('Cl2', 'F3', 1),
                    ('F3', 'Si4', 1), ('Si4', 'C1', 1)]
hubbard = HamHub(system, u_onsite=np.array([1, 1]), 
                 atom_dictionary={'C': 0, 'Cl': 1, 'F': 2, 'Si': 3},
                 bond_dictionary={'CCl': 0, 'ClF': 1, 'FSi': 2, 'SiC': 3})

print(hubbard.generate_one_body_integral(dense=True, basis='spatial basis'))

[[0. 0. 0. 3.]
 [0. 1. 1. 0.]
 [0. 1. 2. 2.]
 [3. 0. 2. 3.]]
